server:
  port: 9528
spring:
  application:
    name: cloud-geteway
  cloud:
    gateway:
      routes:
        - id: payment_routh   #路由的id 没有固定规则但要求唯一
#          uri: http://localhost:8001   #匹配后提供的服务路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/dept/create/**
             # - After=2020-12-15T17:28:53.524+08:00[Asia/Shanghai] 在什么时间之后才可以访问
              # - Before=2020-12-15T16:28:53.524+08:00[Asia/Shanghai]
              # - Between=2020-12-15T16:28:53.524+08:00[Asia/Shanghai],2020-12-15T17:28:53.524+08:00[Asia/Shanghai]
            # - Cookie=username,zzjj 根据cookie值访问不对职不访问
             # - Header=X-Request-Id,\d+ 请求头要有x-request-id属性并且值为整数
        - id: payment_routh2   #路由的id 没有固定规则但要求唯一
#          uri: http://localhost:8001   #匹配后提供的服务路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true  #开启从服务中心动态创建路由功能利用微服务名进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
