server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由id 没有固定规格但要求统一 建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          uri: lb://cloud-payment-service
          predicates:
            - Path=/dept/create/**  # 断言 路径相匹配的进行路由

        - id: payment_routh2
          uri: http://localhost:8001
#          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            # - Cookie=username,zzjj
            # - Header=X-Request-Id,\d+
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
